# Generated by Django 3.1.4 on 2021-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='desc_hospital',
            field=models.TextField(blank=True, null=True),
        ),
    ]
